name: Bunker
author: Remag501
version: 1.2
main: me.remag501.bunker.Bunker
api-version: '1.19'
description: "Custom plugin for battlegrounds that allows creation and management of bunkers"

commands:
  bunker:
    description: 'Use bunker'
    usage: '/bunker [args]'
    aliases: ['b']
    permission: 'bunker.command'
  bunkeradmin:
    description: 'Manage bunkers as admin'
    usage: '/bunkeradmin [args]'
    aliases: ['ba']
    permission: 'bunkeradmin.command'



depend:
  - WorldEdit
  - Multiverse-Core
  - Citizens
  - VoidGen
  - DecentHolograms
  - KGenerators
  - WorldGuard
  - AxVaults

softdepend:
  - PlaceholderAPI