name: Bunker
author: Remag501
version: 1.1
main: me.remag501.bunker.Bunker
# api-version: '1.21'

commands:
  bunker:
    description: 'Manage bunkers'
    usage: '/bunker <command> [args]'
    aliases: ['b']
    permission: 'bunker.command'

depend:
  - WorldEdit
  - Multiverse-Core

softdepend:
  - Vault
  - PlaceholderAPI
  - VoidGen