name: Bunker
author: Remag501
version: 1.2
main: me.remag501.bunker.Bunker
api-version: '1.19'
description: "Custom plugin for battlegrounds that allows creation and management of bunkers"

commands:
  # This is the "parent" permission for players
  bunker.use:
    description: Basic access to the bunker command.
    default: true
    children:
      bunker.upgrade: true

  # This is the subcommand permission
  bunker.upgrade:
    description: Ability to use the upgrade subcommand.
    default: true

  # Admin permission
  bunker.admin:
    description: Full administrative control.
    default: op



depend:
  - WorldEdit
  - Multiverse-Core
  - Citizens
  - VoidGen
  - DecentHolograms
  - KGenerators
  - WorldGuard
  - AxVaults

softdepend:
  - PlaceholderAPI