name: Bunker
author: Remag501
version: 1.2
main: me.remag501.bunker.Bunker
api-version: '1.19'
description: "Custom plugin for battlegrounds that allows creation and management of bunkers"

commands:
  bunker:
    description: Access bunker features.
    usage: /bunker [upgrade]
    aliases: [b]
    permission: bunker.use
  bunkeradmin:
    description: Administrative management for bunkers.
    usage: /bunkeradmin <args>
    aliases: [ba]
    permission: bunker.admin

permissions:
  # This is the "parent" permission for players
  bunker.use:
    description: Basic access to the bunker command.
    default: true

  # This is the subcommand permission
  bunker.upgrade:
    description: Ability to use the upgrade subcommand.
    default: true

  # Admin permission
  bunker.admin:
    description: Full administrative control.
    default: op

  # Permission to break your own bunker gen
  bunker.breakgen:
    description: This permission should have been in NextGens
    default: op



depend:
  - WorldEdit
  - Multiverse-Core
  - Citizens
  - VoidGen
  - DecentHolograms
  - WorldGuard
  - AxVaults

softdepend:
  - PlaceholderAPI