name: Bunker
version: '${project.version}'
main: me.remag501.bunker.Bunker
# api-version: '1.21'
commands:
  bunker:
    description: 'Manage bunkers'
    usage: '/bunker <command> [args]'
    aliases: ['b']
    permission: 'bunker.command'
